### ISSUE TITLE
HIVE to REST Catalog Migration Fails with Invalid S3 URI

### ISSUE THREAD

**Issue by ajaykarthick27** [projectnessie/iceberg-catalog-migrator#197]
I'm testing a few catalog migration scenarios, so I've set up a Hive Metastore with warehouse directories pointing to the local filesystem, such as `/tmp/warehouse`. Additionally, I've created a REST catalog with a warehouse location in S3. I used Spark SQL to create test tables, which are registered with the Hive Metastore. Now, I'm attempting to migrate these tables to the REST catalog, but I'm encountering issues related to the file scheme. Despite changing the `IO-IMPL` to `org.apache.iceberg.hadoop.HadoopFileIO`, I'm still getting the following error. I'm not sure what I'm doing wrong here.

**Command Executed**
```bash 
java -jar iceberg-catalog-migrator-cli-0.3.0.jar migrate --stacktrace \
--source-catalog-type HIVE \
--source-catalog-properties warehouse=/tmp/hive/data/warehouse,uri=thrift://hive-metastore:9083 \
--target-catalog-type REST  \
--target-catalog-properties uri=http://rest:8181,io-impl=org.apache.iceberg.aws.s3.S3FileIO,warehouse=s3://warehouse/wh/,s3.endpoint=http://minio:9000 `
```

**Error Log**
```
root@c57a153ccb4d:~# cat logs/catalog_migration.log
2024-08-14 18:12:38,982 [main] INFO  org.apache.iceberg.CatalogUtil - Loading custom FileIO implementation: org.apache.iceberg.aws.s3.S3FileIO
2024-08-14 18:12:41,708 [main] INFO  o.p.t.c.m.api.CatalogMigrator - Collecting all the namespaces from source catalog...
2024-08-14 18:12:41,716 [main] INFO  o.apache.hadoop.hive.conf.HiveConf - Found configuration file null
2024-08-14 18:12:42,100 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-08-14 18:12:42,117 [main] INFO  hive.metastore - Trying to connect to metastore with URI thrift://hive-metastore:9083
2024-08-14 18:12:42,137 [main] INFO  hive.metastore - Opened a connection to metastore, current connections: 1
2024-08-14 18:12:42,169 [main] INFO  hive.metastore - Connected to metastore.
2024-08-14 18:12:42,252 [main] INFO  o.p.t.c.m.api.CatalogMigrator - Collecting all the tables from all the namespaces of source catalog...
2024-08-14 18:12:42,253 [main] WARN  o.p.t.c.m.api.CatalogMigrator - Failed to identify tables from empty namespace : Missing database in namespace:
2024-08-14 18:12:42,350 [main] INFO  o.a.i.BaseMetastoreTableOperations - Refreshing table metadata from new version: file:/tmp/hive/data/warehouse/mig_src.db/simple_table/metadata/00001-a1ec7728-4983-4650-9a7c-405182ed15be.metadata.json
2024-08-14 18:12:42,422 [main] INFO  o.a.iceberg.BaseMetastoreCatalog - Table loaded by catalog: SOURCE_CATALOG_HIVE.mig_src.simple_table
2024-08-14 18:12:42,431 [main] ERROR o.p.t.c.m.api.CatalogMigrator - Unable to register the table mig_src.simple_table
org.apache.iceberg.exceptions.BadRequestException: Malformed request: Invalid S3 URI, cannot determine scheme: file:/tmp/hive/data/warehouse/mig_src.db/simple_table/metadata/00001-a1ec7728-4983-4650-9a7c-405182ed15be.metadata.json
        at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:208)
        at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:118)
        at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:102)
        at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:201)
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:313)
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:252)
        at org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:358)
        at org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)
        at org.apache.iceberg.rest.RESTSessionCatalog.registerTable(RESTSessionCatalog.java:454)
        at org.apache.iceberg.catalog.BaseSessionCatalog$AsCatalog.registerTable(BaseSessionCatalog.java:89)
        at org.apache.iceberg.rest.RESTCatalog.registerTable(RESTCatalog.java:218)
        at org.projectnessie.tools.catalog.migration.api.CatalogMigrator.registerTableToTargetCatalog(CatalogMigrator.java:213)
        at org.projectnessie.tools.catalog.migration.api.CatalogMigrator.registerTable(CatalogMigrator.java:147)
        at org.projectnessie.tools.catalog.migration.cli.BaseRegisterCommand.call(BaseRegisterCommand.java:159)
        at org.projectnessie.tools.catalog.migration.cli.MigrateCommand.call(MigrateCommand.java:63)
        at org.projectnessie.tools.catalog.migration.cli.MigrateCommand.call(MigrateCommand.java:26)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.projectnessie.tools.catalog.migration.cli.CatalogMigrationCLI.main(CatalogMigrationCLI.java:48)
root@c57a153ccb4d:~#
```

**Comment by ismailsimsek** [comment]
@ajaykarthick27 have you found out any solution?

**Comment by ismailsimsek** [comment]
found it, this works for me 

solution is [explained here](https://github.com/apache/iceberg/issues/11113#issuecomment-2345365198):

fix is 

> all I need:
> From: `--conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO`
> To: `--conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.io.ResolvingFileIO`
