### ISSUE TITLE
Migrating from Hive to Nessie getting java.io.IOException: No FileSystem for scheme: hdfs

### ISSUE THREAD

**Issue by wilsonpenha** [projectnessie/iceberg-catalog-migrator#94]
My hadoop env is 3.3.1
my hive env is 3.1.0
my iceberg is 1.2.1
my spark-3.2.1
my nessie-0.59.0 server

export HADOOP_CONF_DIR=/etc/hadoop/conf
export HIVE_CONF_DIR=/etc/hive/conf

java -Djavax.net.ssl.trustStore=/etc/security/clientKeys/client-truststore.jks \
     -Djavax.net.ssl.trustStorePassword=password \
-jar iceberg-catalog-migrator-cli-0.2.1-SNAPSHOT.jar register \
--source-catalog-type HIVE \
--source-catalog-properties warehouse=hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/,uri=thrift://hive-metastore:9083 \
--identifiers hive_data.t_ers_event_perf,hive_data.T_KWH_MATCH_RECORD_PERF \
--target-catalog-type NESSIE \
--target-catalog-properties uri=http://localhost:19120/api/v1,ref=main,warehouse=hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive

$ cat logs/catalog_migration.log 
2023-10-07 00:30:19,852 [main] INFO  o.apache.hadoop.hive.conf.HiveConf - Found configuration file file:/usr/lib/spark/conf/hive-site.xml
2023-10-07 00:30:20,186 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.tez.cartesian-product.enabled does not exist
2023-10-07 00:30:20,186 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.warehouse.external.dir does not exist
2023-10-07 00:30:20,186 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.heapsize does not exist
2023-10-07 00:30:20,186 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.materializedview.rewriting.incremental does not exist
2023-10-07 00:30:20,186 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.server2.webui.cors.allowed.headers does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.hook.proto.base-directory does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.load.data.owner does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.max-partitions-per-writers does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.service.metrics.codahale.reporter.classes does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.strict.managed.tables does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.ignore-absent-partitions does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.create.as.insert.only does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.server2.webui.enable.cors does not exist
2023-10-07 00:30:20,187 [main] WARN  o.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.db.type does not exist
2023-10-07 00:30:20,422 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-10-07 00:30:20,440 [main] INFO  hive.metastore - Trying to connect to metastore with URI thrift://hive-metastore:9083
2023-10-07 00:30:20,498 [main] INFO  hive.metastore - Opened an SSL connection to metastore, current connections: 1
2023-10-07 00:30:20,851 [main] INFO  hive.metastore - Connected to metastore.
2023-10-07 00:30:21,116 [main] INFO  o.a.i.BaseMetastoreTableOperations - Refreshing table metadata from new version: hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/hive_data.db/T_ERS_EVENT_PERF/metadata/00003-f70dd253-791a-499e-9ebd-7a739a461960.metadata.json
2023-10-07 00:30:21,160 [main] WARN  org.apache.iceberg.util.Tasks - Retrying task after failure: Failed to get file system for path: hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/hive_data.db/T_ERS_EVENT_PERF/metadata/00003-f70dd253-791a-499e-9ebd-7a739a461960.metadata.json
org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/hive_data.db/T_ERS_EVENT_PERF/metadata/00003-f70dd253-791a-499e-9ebd-7a739a461960.metadata.json
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:58)
	at org.apache.iceberg.hadoop.HadoopInputFile.fromLocation(HadoopInputFile.java:56)
	at org.apache.iceberg.hadoop.HadoopFileIO.newInputFile(HadoopFileIO.java:90)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:266)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$0(BaseMetastoreTableOperations.java:189)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$1(BaseMetastoreTableOperations.java:208)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:208)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:185)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:180)
	at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:176)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80)
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47)
	at org.projectnessie.tools.catalog.migration.api.CatalogMigrator.registerTableToTargetCatalog(CatalogMigrator.java:212)
	at org.projectnessie.tools.catalog.migration.api.CatalogMigrator.registerTable(CatalogMigrator.java:147)
	at org.projectnessie.tools.catalog.migration.cli.BaseRegisterCommand.call(BaseRegisterCommand.java:159)
	at org.projectnessie.tools.catalog.migration.cli.BaseRegisterCommand.call(BaseRegisterCommand.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.projectnessie.tools.catalog.migration.cli.CatalogMigrationCLI.main(CatalogMigrationCLI.java:48)
Caused by: java.io.IOException: No FileSystem for scheme: hdfs
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:56)
	... 29 common frames omitted
2023-10-07 00:30:21,272 [main] WARN  org.apache.iceberg.util.Tasks - Retrying task after failure: Failed to get file system for path: hdfs://hadoopcluster/sin/ers/warehouse/tablespa..........

same error over and over

**Comment by ajantha-bhat** [comment]
>  Failed to get file system for path: hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/hive_data.db/T_ERS_EVENT_PERF/metadata/00003-f70dd253-791a-499e-9ebd-7a739a461960.metadata.json

Since you are using HDFS file system. You can check if any hadoop conf required to be set. You can use `--source-catalog-hadoop-conf` CLI option.

**Comment by wilsonpenha** [comment]
Well this is my first time using it so I don't know what to provide for this property and also the both HADOOP_CONF_DIR and HIVE_CONF_DIR are set so please provide what should I set?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wilsonpenha** [comment]
> > Failed to get file system for path: hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive/hive_data.db/T_ERS_EVENT_PERF/metadata/00003-f70dd253-791a-499e-9ebd-7a739a461960.metadata.json
> 
> Since you are using HDFS file system. You can check if any hadoop conf required to be set. You can use `--source-catalog-hadoop-conf` CLI option.

I've added this and still not working:
     --source-catalog-hadoop-conf fs.defaultFS6="hdfs://hadoopcluster",\
fs.gs.application.name.suffix="(GPN:Hortonworks; version 1.0) HDP/None",\
fs.gs.path.encoding="uri-path",\
fs.gs.working.dir="/",\
fs.s3a.fast.upload="true",\
fs.s3a.fast.upload.buffer="disk",\
fs.s3a.multipart.size="67108864",\
fs.s3a.user.agent.prefix="User-Agent: APN/1.0 Hortonworks/1.0 HDP/None",\
fs.trash.interval="360",\
ha.failover-controller.active-standby-elector.zk.op.retries="120",\
ha.zookeeper.quorum="hadoophbase1:2181;hadoopnn1:2181;hadoopnn2:2181",\
hadoop.http.authentication.simple.anonymous.allowed="true",\
hadoop.http.cross-origin.allowed-headers="X-Requested-With;Content-Type;Accept;Origin;WWW-Authenticate;Accept-Encoding;Transfer-Encoding",\
hadoop.http.cross-origin.allowed-methods="GET;PUT;POST;OPTIONS;HEAD;DELETE",\
hadoop.http.cross-origin.allowed-origins="*",\
hadoop.http.cross-origin.max-age="1800",\
hadoop.http.filter.initializers="org.apache.hadoop.security.AuthenticationFilterInitializer;org.apache.hadoop.security.HttpCrossOriginFilterInitializer",\
hadoop.http.staticuser.user="yarn",\
hadoop.proxyuser.ambari.groups="*",\
hadoop.proxyuser.ambari.hosts="*",\
hadoop.proxyuser.hbase.groups="*",\
hadoop.proxyuser.hbase.hosts="*",\
hadoop.proxyuser.hive.groups="*",\
hadoop.proxyuser.hive.hosts="*",\
hadoop.proxyuser.oozie.groups="*",\
hadoop.proxyuser.oozie.hosts="*",\
hadoop.security.auth_to_local="DEFAULT",\
hadoop.security.authentication="simple",\
hadoop.security.authorization="false",\
hadoop.security.instrumentation.requires.admin="false",\
hadoop.security.key.provider.path="kms://https@hadoopnn2;hadoopyarn1:9393/kms",\
hadoop.ssl.hostname.verifier="DEFAULT",\
hadoop.ssl.keystores.factory.class="org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory",\
hadoop.ssl.require.client.cert="false",\
io.compression.codecs="org.apache.hadoop.io.compress.GzipCodec;org.apache.hadoop.io.compress.DefaultCodec;org.apache.hadoop.io.compress.SnappyCodec",\
io.file.buffer.size="131072",\
io.serializations="org.apache.hadoop.io.serializer.WritableSerialization",\
ipc.client.connect.max.retries="50",\
ipc.client.connection.maxidletime="30000",\
ipc.client.idlethreshold="8000",\
ipc.server.tcpnodelay="true",\
mapreduce.jobtracker.webinterface.trusted="false",\
net.topology.script.file.name="/etc/hadoop/conf/topology_script.py",\
spark.authenticate="true",\
dfs.block.access.token.enable="true",\
dfs.blockreport.initialDelay="120",\
dfs.blocksize="536870912",\
dfs.client.failover.proxy.provider.hadoopcluster="org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",\
dfs.client.https.need-auth="false",\
dfs.client.read.shortcircuit="true",\
dfs.client.read.shortcircuit.streams.cache.size="4096",\
dfs.client.retry.policy.enabled="false",\
dfs.cluster.administrators="hdfs",\
dfs.content-summary.limit="5000",\
dfs.datanode.address="0.0.0.0:50010",\
dfs.datanode.balance.bandwidthPerSec="6250000",\
dfs.datanode.data.dir="/data1/dfs/dn",\
dfs.datanode.data.dir.perm="750",\
dfs.datanode.du.reserved="1073741824",\
dfs.datanode.failed.volumes.tolerated="0",\
dfs.datanode.http.address="0.0.0.0:50075",\
dfs.datanode.https.address="0.0.0.0:50475",\
dfs.datanode.ipc.address="0.0.0.0:8010",\
dfs.datanode.max.transfer.threads="1024",\
dfs.disk.balancer.enabled="true",\
dfs.domain.socket.path="/var/lib/hadoop-hdfs/dn_socket",\
dfs.encrypt.data.transfer.cipher.suites="AES/CTR/NoPadding",\
dfs.encryption.key.provider.uri="kms://https@hadoopnn2;hadoopyarn1:9393/kms",\
dfs.ha.automatic-failover.enabled="true",\
dfs.ha.fencing.methods="shell(/bin/true)",\
dfs.ha.namenodes.hadoopcluster="nn1;nn2",\
dfs.heartbeat.interval="3",\
dfs.hosts.exclude="/etc/hadoop/conf/dfs.exclude",\
dfs.http.policy="HTTPS_ONLY",\
dfs.https.port="50470",\
dfs.internal.nameservices="hadoopcluster",\
dfs.journalnode.edits.dir="/hadoop/hdfs/journalnode",\
dfs.journalnode.http-address="0.0.0.0:8480",\
dfs.journalnode.https-address="0.0.0.0:8481",\
dfs.namenode.accesstime.precision="0",\
dfs.namenode.acls.enabled="true",\
dfs.namenode.audit.log.async="true",\
dfs.namenode.avoid.read.stale.datanode="true",\
dfs.namenode.avoid.write.stale.datanode="true",\
dfs.namenode.checkpoint.dir="/hadoop/hdfs/namesecondary",\
dfs.namenode.checkpoint.period="21600",\
dfs.namenode.checkpoint.txns="1000000",\
dfs.namenode.fslock.fair="false",\
dfs.namenode.handler.count="100",\
dfs.namenode.http-address.hadoopcluster.nn1="hadoopnn1:50070",\
dfs.namenode.http-address.hadoopcluster.nn2="hadoopnn2:50070",\
dfs.namenode.https-address.hadoopcluster.nn1="hadoopnn1:50470",\
dfs.namenode.https-address.hadoopcluster.nn2="hadoopnn2:50470",\
dfs.namenode.inode.attributes.provider.class="org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer",\
dfs.namenode.name.dir="/data1/dfs/nn",\
dfs.namenode.name.dir.restore="true",\
dfs.namenode.rpc-address.hadoopcluster.nn1="hadoopnn1:8020",\
dfs.namenode.rpc-address.hadoopcluster.nn2="hadoopnn2:8020",\
dfs.namenode.safemode.threshold-pct="0.999",\
dfs.namenode.secondary.http-address="localhost:50090",\
dfs.namenode.shared.edits.dir="qjournal://hadoophbase1:8485;hadoopnn1:8485;hadoopnn2:8485/hadoopcluster",\
dfs.namenode.stale.datanode.interval="30000",\
dfs.namenode.startup.delay.block.deletion.sec="3600",\
dfs.namenode.write.stale.datanode.ratio="1.0f",\
dfs.nameservices="hadoopcluster",\
dfs.permissions.ContentSummary.subAccess="false",\
dfs.permissions.enabled="true",\
dfs.permissions.superusergroup="hdfs",\
dfs.replication="3",\
dfs.replication.max="50",\
dfs.webhdfs.enabled="true",\
fs.permissions.umask-mode="022",\
hadoop.caller.context.enabled="true",\
manage.include.files="false",\
nfs.exports.allowed.hosts="* rw",\
nfs.file.dump.dir="/tmp/.hdfs-nfs" \

**Comment by ajantha-bhat** [comment]
Pasting the solution from Zuliip chat discussions



- adding this line to cli/build.gradle.kts
implementation(libs.hadoop.hdfs)

- changing hadoop version at libs.version.toml
hadoop = "3.3.1" # this is in mapping with iceberg repo.
then running the follow command
export HADOOP_CONF_DIR=/usr/lib/spark/conf
export HIVE_CONF_DIR=/usr/lib/spark/conf

- building a new jar (iceberg-catalog-migrator-cli-0.2.1-SNAPSHOT.jar)

```
java -Djavax.net.ssl.trustStore=/etc/security/clientKeys/client-truststore.jks \
-Djavax.net.ssl.trustStorePassword=admin1234 \
-Dhadoop.configuration.addResources=$HADOOP_CONF_DIR/core-site.xml \
-Dhadoop.configuration.addResources=$HADOOP_CONF_DIR/hdfs-site.xml \
-Dhadoop.configuration.addResources=$HADOOP_CONF_DIR/hive-site.xml \
-jar iceberg-catalog-migrator-cli-0.2.1-SNAPSHOT.jar \
register \
--source-catalog-type HIVE \
--source-catalog-properties warehouse=hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive,uri=thrift://hadoopoozie1:9083 \
--identifiers hive_data.t_ers_event_perf,hive_data.T_KWH_MATCH_RECORD_PERF \
--target-catalog-type NESSIE \
--target-catalog-properties uri=http://localhost:19120/api/v1,ref=main,warehouse=hdfs://hadoopcluster/sin/ers/warehouse/tablespace/external/hive
```

**Comment by wilsonpenha** [comment]
Hey I forgot to mention the solution here which would means change the code base here by someone or you guys may want to test it more?

**Comment by ajantha-bhat** [comment]
I think we can test it more with manually supplement the jar in class path and use hadoop 2.7.3

**Comment by wilsonpenha** [comment]
The problem with Hadoop 2.7.3 is that it uses sun.nio.ch.DirectBuffer.cleaner() from java1.8 which was removed from java11 causing exception
At final stage of FileInputStream, I looked into the java code and tested that it won't work with java11 you can see the stacktrace at zullichat another thing is we use hadoop3.3.1 so we could try Hadoop3.0.0 anyway that could be different version like one for Hadoop2 and another for Hadoop3 like spark what do you think?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
